name: "Test pipeline"

on:
  workflow_dispatch:
    inputs:
      view:
        description: "View name"
        required: true
        type: string
      description:
        description: "Short description"
        required: true
        type: string

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Print inputs
        run: |
          echo "ClearCase view: ${{ inputs.view }}"
          echo "Description:: ${{ inputs.description }}"
